language: go
go:
- '1.12'

script:
- make dist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob:
  file: terraform-provider-k8s_$TRAVIS_TAG*
  skip_cleanup: true
  on:
    tags: true
