# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true
#

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.3"

[[override]]
  name = "github.com/agext/levenshtein"
  version = "v1.2.1"

[[override]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "2bd8b58cf4275aeb086ade613de226773e29e853"

[[override]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"

[[override]]
  name = "github.com/armon/go-radix"
  revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.12.70"

[[override]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"

[[override]]
  name = "github.com/bgentry/speakeasy"
  version = "v0.1.0"

[[override]]
  name = "github.com/blang/semver"
  version = "v3.5.1"

[[override]]
  name = "github.com/go-ini/ini"
  version = "v1.32.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.0.0"

[[override]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"

[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "d5fe4b57a186c716b0e00b8c301cbd9b4182694d"

[[override]]
  name = "github.com/hashicorp/go-getter"
  revision = "285374cdfad63de2c43d7562f49ced6dde5a7ba0"

[[override]]
  name = "github.com/hashicorp/go-hclog"
  revision = "5bcb0f17e36442247290887cc914a6e507afa5c4"

[[override]]
  name = "github.com/hashicorp/go-multierror"
  revision = "b7773ae218740a7be65057fc60b366a49b538a44"

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "e53f54cbf51efde642d4711313e829a1ff0c236d"

[[override]]
  name = "github.com/hashicorp/go-uuid"
  revision = "64130c7a86d732268a38cb04cfbaf0cc987fda98"

[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "4fe82ae3040f80a03d04d2cccb5606a626b8e1ee"

[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "23c074d0eceb2b8a5bfdbb271ab780cde70f05a8"

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "9f91684a1f1714c19f6d84313454f70b3773a300"

[[override]]
  name = "github.com/hashicorp/hil"
  revision = "fa9f258a92500514cc8e9c67020487709df92432"

[[override]]
  name = "github.com/hashicorp/yamux"
  revision = "683f49123a33db61abfb241b7ac5e4af4dc54d55"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "0b12d6b5"

[[override]]
  name = "github.com/mattn/go-isatty"
  version = "v0.0.3"

[[override]]
  name = "github.com/mitchellh/cli"
  revision = "518dc677a1e1222682f4e7db06721942cb8e9e4c"

[[override]]
  name = "github.com/mitchellh/copystructure"
  revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"

[[override]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"

[[override]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "a61a99592b77c9ba629d254a693acffaeb4b7e28"

[[override]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"

[[override]]
  name = "github.com/mitchellh/hashstructure"
  revision = "2bca23e0e452137f789efbc8610126fd8b94f73b"

[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "b4575eea38cca1123ec2dc90c26529b5c5acfcff"

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "63d60e9d0dbc60cf9164e6510889b0db6683d98c"

[[override]]
  name = "github.com/oklog/run"
  version = "v1.0.0"

[[override]]
  name = "github.com/posener/complete"
  version = "v1.1"

[[override]]
  name = "github.com/satori/go.uuid"
  version = "v1.2.0"

[[override]]
  name = "github.com/ulikunitz/xz"
  version = "v0.5.4"

[[override]]
  name = "github.com/zclconf/go-cty"
  revision = "709e4033eeb037dc543dbc2048065dfb814ce316"

[[override]]
  name = "golang.org/x/crypto"
  revision = "1875d0a70c90e57f11972aefd42276df65e895b9"

[[override]]
  name = "golang.org/x/net"
  revision = "2fb46b16b8dda405028c50f7c7f0f9dd1fa6bfb1"

[[override]]
  name = "golang.org/x/sys"
  revision = "37707fdb30a5b38865cfb95e5aab41707daec7fd"

[[override]]
  name = "golang.org/x/text"
  revision = "e19ae1496984b1c655b8044a65c0300a3c878dd3"

[[override]]
  name = "google.golang.org/genproto"
  revision = "4eb30f4778eed4c258ba66527a0d4f9ec8a36c45"

[[override]]
  name = "google.golang.org/grpc"
  version = "v1.9.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
